services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - REDIS_URI=redis://redis:6379
      - NODE_ENV=production
      - CORS_ALLOWED_ORIGIN_ONE=https://zyramoments.in
      - CORS_ALLOWED_ORIGIN_TWO=https://www.zyramoments.in
      - CORS_ALLOWED_ORIGIN_LOCAL=http://localhost:5173
      - DATABASE_URI=mongodb+srv://albinpariyarath:BPpLWkO7GqMfRJSw@zyraeventscluster.q9pgf.mongodb.net/zyra-moments?retryWrites=true&w=majority&appName=zyraEventsCluster
      - EMAIL_USER=zyramoments.org@gmail.com
      - EMAIL_PASS=zspa bwtv nstp ofjh
      - JWT_SECRET_KEY=01071ad1938f50750fbd23e54b26fa10ea14ae1bd73ff38fa8574710059db438876510160e24e00a9b38
      - JWT_ACCESS_EXPIRES_IN=1d
      - JWT_REFRSH_EXPIRES_IN=7d
      - STRIPE_PK=pk_test_51QE3X1K0oDaPVFn3LIORvughq1FbieLfPX2EsvTWv5Qze2L5lcCfoYbgaPzu631Y3bigxeNTNLdB6qIppsRTrZ9s00Ryy6xijQ
      - STRIPE_SK=sk_test_51QE3X1K0oDaPVFn3rNQhFFabqyMkvmNda6HVrwezGdpeMyfxkteJO9EHHhavgNh9wLqStjs5TksQo0aJznq1WpxX003k9zyQpJ
      - STRIPE_WEBHOOK_SECRET=whsec_DRSdUCRulCVdA0absGSn2dfsLeMe6jam
    depends_on:
      - redis
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
